# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'
target 'CommunicationUI-Proxy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CommunicationUI-Proxy
  # pod 'AzureCommunicationUICalling', '1.13.0'
  pod 'AzureCommunicationUICalling', :git => 'https://github.com/billylo1/communication-ui-library-ios.git', :commit => '11210b048e880f8aa4c67c0327ad8dd7faaa5f26'
  
end
