# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'
target 'CommunicationUI-Proxy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CommunicationUI-Proxy
  pod 'AzureCommunicationUICalling', :git => 'https://github.com/billylo1/communication-ui-library-ios.git', :branch => 'Attempt2', :commit => '7358af12fe5b3786bd02a92d0dc7c1b836794ef9'

end
